# Generated by Django 4.1.3 on 2022-12-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_alter_familiar_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=100)),
            ],
        ),
    ]
